# Buildez individuellement chaque image docker
# Commande : docker-compose up -d

version: '2'

services:

  # The external partners, implemented as .Net services
  do_dotnet_server:
    image: do_dotnet_server
    container_name: do_dotnet_server
    expose:
      - "9090"
    ports:
      - "9090:9090"

  # The Cookie on Demand service, a J2E system
  do_backend:
   image: do_backend
   container_name: do_backend
   environment:
     - bank_host=tcf_partners
     - bank_port=9090
   expose:
     - "8080"
   ports:
     - "8080:8080"
   depends_on:
     - do_dotnet_server
